#ifndef CSC10002_DATA_STRUCTURE_VISUALIZER_WINDOWSLIST_H
#define CSC10002_DATA_STRUCTURE_VISUALIZER_WINDOWSLIST_H
enum windowType{
    mainMenuWindow,
    selectingMenuWindow,
    singlyLinkedListWindow
};
#endif //CSC10002_DATA_STRUCTURE_VISUALIZER_WINDOWSLIST_H
